=== Sxcram02/1-daw/clases/Lenguaje/P4.228.marcos/XSD/pedido.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="cliente" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                    <xs:element name="apellido" type="xs:string"></xs:element>
                                </xs:sequence>
                                <xs:attribute name="codigo" type="xs:int"></xs:attribute>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="articulos" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="descripcion" type="xs:string"></xs:element>
                                                <xs:element name="cantidad" type="xs:int"></xs:element>
                                                <xs:element name="precio" type="xs:float"></xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="total" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                                <xs:attribute name="valor" type="xs:float"></xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                        <xs:attribute name="numero" type="xs:int" use="required"></xs:attribute>
                        <xs:attribute name="dia" type="xs:date" use="optional"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Sxcram02/1-daw/Lenguaje/P4.228.marcos/.history/XML/pedido2_20230130234802.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/pedido.xsd">
    <pedido numero="26" dia="2023-12-01">
        <cliente codigo="20">
            <nombre> Felipe </nombre>
            <apellido> Garcia </apellido>
        </cliente>
        <articulos>
            <articulo>
                <descripcion>Yoda Mimobot USB Flash Drive 8GB</descripcion>
                <cantidad>5</cantidad>
                <precio>38.99</precio>
            </articulo>
            <articulo>
                <descripcion>Darth Vader Half Helmet Case for iPhone</descripcion>
                <cantidad>2</cantidad>
                <precio>29.95</precio>
            </articulo>
        </articulos>
        <total valor="254.85"></total>
    </pedido>
</pedido>
