=== Sxcram02/1-daw/Lenguaje/Examen/Practica1/vuelos.dtd
<!ELEMENT helipuerto (nombre,vuelos+,fecha)*>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT vuelos (vuelo+)>
        <!ELEMENT vuelo (diario?,origen,destino,salida,llegada)>
            <!ATTLIST vuelo codigo ID #REQUIRED>
            <!ATTLIST vuelo estado NOTATION (E|R|C) "E">
                <!NOTATION E SYSTEM 'en hora'>
                <!NOTATION R SYSTEM 'retraso'>
                <!NOTATION C SYSTEM 'cancelado'>
            <!ELEMENT diario EMPTY>
            <!ELEMENT origen (#PCDATA)>
            <!ELEMENT destino (#PCDATA)>
            <!ELEMENT salida (#PCDATA)>
            <!ELEMENT llegada (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>

=== Sxcram02/1-daw/Lenguaje/Examen/Practica1/vuelos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE helipuerto SYSTEM "vuelos.dtd">
<helipuerto>
    <nombre>JCU</nombre>
    <vuelos>
        <vuelo codigo="V123" estado="E">
            <diario>SI</diario>
            <origen>Ceuta</origen>
            <destino>Málaga</destino>
            <salida>9:30</salida>
            <llegada>10:00</llegada>
        </vuelo>
        <vuelo codigo="V124" estado="R">
            <diario></diario>
            <origen>Algeciras</origen>
            <destino>Ceuta</destino>
            <salida>10:15</salida>
            <llegada>10:20</llegada>
        </vuelo>
        <vuelo codigo="V125" estado="C">
            <diario>SI</diario>
            <origen>Málaga</origen>
            <destino>Ceuta</destino>
            <salida>10:30</salida>
            <llegada>10:50</llegada>
        </vuelo>
    </vuelos>
    <fecha>9-02-2023</fecha>
</helipuerto>
