=== Sxcram02/1-daw/Lenguaje/DTD/cine.dtd
<!ELEMENT cine (directores,peliculas)>
    <!ELEMENT directores (director)*>
        <!ELEMENT director (#PCDATA)>
        <!ATTLIST director coddir ID #REQUIRED>

    <!ELEMENT peliculas (pelicula)*>
        <!ELEMENT pelicula (#PCDATA)>
            <!ATTLIST pelicula direccion IDREF #REQUIRED>

=== Sxcram02/1-daw/Lenguaje/XML/Ejercicio22.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE cine SYSTEM "cine.dtd">
<cine>
    <directores>
        <director coddir="CE">Clint Eastwood</director>
        <director coddir="JC">James Cameron</director>
    </directores>
    <peliculas>
        <pelicula direccion="JC">Avatar</pelicula>
        <pelicula direccion="CE">Mystic River</pelicula>
        <pelicula direccion="JC">Titanic</pelicula>
    </peliculas>
</cine>
