=== Sxcram02/1-daw/Lenguaje/DTD/persona2.dtd
<!ELEMENT persona (nombre, apellidos, fechaDeNacimiento, ciudad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fechaDeNacimiento (dia,mes,ano)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

=== Sxcram02/1-daw/clases/Lenguaje/XML/Ejercicio14.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE persona SYSTEM "../DTD/persona2.dtd">
<persona>
    <nombre>Marcos</nombre>
    <apellidos>Dominguez Vega</apellidos>
    <fechaDeNacimiento>
        <dia>15</dia>
        <mes>04</mes>
        <ano>2002</ano>
    </fechaDeNacimiento>
    <ciudad>Madrid</ciudad>
</persona>
