=== Sxcram02/1-daw/clases/Lenguaje/P4.228.marcos/DTD/factura.dtd
<!ELEMENT factura (datosEmisor, datosCliente, detallesFactura)>
    <!ATTLIST factura numero CDATA #REQUIRED>
    <!ATTLIST factura fecha NMTOKEN #REQUIRED>
    <!ELEMENT datosEmisor (nombre+, apellidos?, cif, telefono*)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT cif (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT datosCliente (nombre+, cif+, telefono*)>
    <!ELEMENT detallesFactura (articulo+)>
        <!ATTLIST detallesFactura importe CDATA #REQUIRED>
        <!ATTLIST detallesFactura moneda (euro|dolar) #REQUIRED>
        <!ATTLIST articulo codigoArticulo ID #REQUIRED>
        <!ATTLIST articulo tipo (Libro|Manual|Varios) #IMPLIED>
        <!ELEMENT articulo (descripcion?, cantidad*, oferta?, pvp)>
            <!ELEMENT descripcion (#PCDATA)>
            <!ELEMENT cantidad (#PCDATA)>
            <!ELEMENT oferta EMPTY>
            <!ELEMENT pvp (#PCDATA)>
                <!ATTLIST pvp moneda (euro|dolar) #REQUIRED>

=== Sxcram02/1-daw/Lenguaje/P4.228.marcos/XML/factura.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE factura SYSTEM "../DTD/factura.dtd">
<factura numero="27" fecha="18-12-2022">
    <datosEmisor>
        <nombre>Pérez</nombre>
        <apellidos>Librería</apellidos>
        <cif>44556677Y</cif>
        <telefono>9566529943</telefono>
    </datosEmisor>
    <datosCliente>
        <nombre>Biblioteca CIFP</nombre>
        <cif>45895623T</cif>
        <telefono>956513490</telefono>
    </datosCliente>
    <detallesFactura importe="85" moneda="euro">
        <articulo codigoArticulo="T3C" tipo="Libro">
            <descripcion>Trilogía de los 3 cuerpos</descripcion>
            <cantidad>1</cantidad>
            <oferta>SI</oferta>
            <pvp moneda="euro">25</pvp>
        </articulo>
        <articulo codigoArticulo="CLR" tipo="Manual">
            <descripcion>Código limpio</descripcion>
            <cantidad>2</cantidad>
            <oferta></oferta>
            <pvp moneda="euro">30</pvp>
        </articulo>
    </detallesFactura>
</factura>
